Releases
########

Current stable releases:

- `WinPython 3.4 <http://sourceforge.net/projects/stonebig.u/files/Winpython_3.4>`_
- `WinPython 3.5 <http://sourceforge.net/projects/stonebig.u/files/Winpython_3.5>`_
- `WinPython 3.6 <http://sourceforge.net/projects/stonebig.u/files/Winpython_3.6>`_

Minimal releases, WinPythonZERO:
- do Provide only a minimimal subset: tkinter, pyodbc, pythonnet, ...
- do exist also for `WinPython 2.7 <http://sourceforge.net/projects/stonebig.u/files/Winpython_2.7>`_


Flavors
#######

`Winpython_Flavors <http://sourceforge.net/projects/stonebig.u/files/Winpython_flavors>`_ are Winpython stable release augmented of a few packages or tools.

Flavors Made : (one time) 

- FlavorKivy = Winpython 2014-10 + Kivy-1.8.0 + pygame-1.9.2a0 (games creation oriented)
- FlavorIgraph = Winpython 2014-10 + pycairo-1.10.0 + python-igraph-0.7.0 (network analysis complement)